In [3]:
#shuffle
import numpy as np
arr = np.arange(9).reshape((3,3))
np.random.shuffle(arr)
print(arr)

[[6 7 8]
 [0 1 2]
 [3 4 5]]


In [6]:
import numpy as np
x = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
y = np.linalg.inv(x)
print(x)
print(y)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [8]:
x=np.linalg.solve(np.array([[1.0, 2.0], [3, 4]]),np.array([8.0,  18.0]))
print(x)

[2. 3.]


In [10]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8]) 
np.where(a==b)


(array([1, 3, 5, 7]),)

In [15]:
import numpy as np
array = np.array([9,4,15,0,17])
argsort_array = array.argsort()
ranks_array = np.empty_like(argsort_array)
ranks_array[argsort_array] = np.arange(len(array))
print(ranks_array)

[2 1 3 0 4]
