In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/surya/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/surya/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/surya/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

In [3]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [7]:
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [9]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.86336782 0.94065703 0.62977424]
  [0.9565241  0.62196845 0.4057377 ]
  [0.48129698 0.39524338 0.46383629]]

 [[0.36291353 0.18465289 0.06894522]
  [0.32602146 0.96562918 0.99110003]
  [0.93498056 0.09521053 0.17129892]]

 [[0.37465656 0.1650609  0.71400647]
  [0.22242254 0.41978753 0.64243416]
  [0.69565722 0.14921927 0.39502404]]]


In [11]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.015379074093395118 0.9955754641586356


In [12]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.566784932857405


In [13]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0

In [14]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [15]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [16]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [18]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.88654278 0.09127376 0.30804576 0.9528481  0.15214304]
 [0.78852936 0.44525768 0.29103998 0.92215434 0.82759048]
 [0.97718573 0.53677133 0.08861035 0.87252111 0.28755646]
 [0.57387991 0.12169888 0.39340405 0.0190066  0.05019727]
 [1.         0.12945314 0.         0.21132497 0.71350566]]


In [20]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [21]:
np.sum(range(5),-1)

10

In [22]:
sum(range(5),-1)

9

In [23]:
help(np.sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

In [24]:
print(np.array(0) // np.array(0))
print(np.array(0) // np.array(0.))
print(np.array(0) / np.array(0))
print(np.array(0) / np.array(0.))

0
nan
nan
nan


<ipython-input-24-b7aafe4ac6f2>:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-24-b7aafe4ac6f2>:2: RuntimeWarning: invalid value encountered in floor_divide
  print(np.array(0) // np.array(0.))
<ipython-input-24-b7aafe4ac6f2>:3: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-24-b7aafe4ac6f2>:4: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0.))


In [25]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[0. 0. 1. 8. 0. 3. 5. 8. 7. 3.]
[0. 0. 1. 8. 0. 3. 5. 8. 7. 3.]
[0. 0. 1. 8. 0. 3. 5. 8. 7. 3.]
[0 0 1 8 0 3 5 8 7 3]
[0. 0. 1. 8. 0. 3. 5. 8. 7. 3.]


In [26]:
Z = np.zeros((5,5))
Z = Z+np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [27]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [28]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [29]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.00791906 0.09409041 0.10369159 0.20613969 0.43697343 0.49421513
 0.58633203 0.71370604 0.74282707 0.74405304]


In [30]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [31]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.all(A==B)

False

In [32]:
Z = np.zeros(10)
Z.flags.writeable = False
#Z[0] = 1

In [33]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.90798761 1.07820412 1.13523092 0.66153685 1.1786979  0.95500474
 1.17026938 0.84716544 0.30068019 1.03350877]
[1.08883072 0.77211307 1.07730705 0.24269755 0.72491445 0.80698385
 0.68948921 1.33802215 1.28216371 1.15223369]


In [34]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.36967855 1.15512587 0.87063705 0.62754517 0.60755874 1.15689421
 0.20545241 0.84113968 1.13825098 0.46418902]
[0.8176454  0.91806931 1.42833482 0.06879383 1.49155406 0.91700919
 0.29589979 0.53873868 0.5545126  1.38099171]


In [35]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [36]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [37]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [38]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [39]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

69


In [40]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),
                  ('color', [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-40-183244f52be5>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),


In [41]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
D.shape

(10, 10)

In [42]:
Z = np.arange(10, dtype=np.int32)
print(Z)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [43]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [44]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [45]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),100)
print(Z)

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [100.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. 100.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]


In [46]:
X = np.random.rand(5, 10)
print(X,"\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.7774652  0.71560023 0.83976709 0.59803305 0.51420551 0.17684315
  0.78908437 0.69383016 0.85927322 0.35553763]
 [0.87049151 0.97106981 0.71319902 0.55069687 0.48452407 0.58993668
  0.86228794 0.12498219 0.59297516 0.12442474]
 [0.24997982 0.34606598 0.41717753 0.78020779 0.90624831 0.50097707
  0.55646102 0.80468516 0.69556252 0.06292953]
 [0.84024544 0.38224422 0.26013859 0.13592236 0.84104605 0.57743493
  0.50033161 0.91755082 0.18808607 0.0282986 ]
 [0.91266374 0.753726   0.83439856 0.73865012 0.27502874 0.43035134
  0.06569871 0.65164788 0.17721388 0.77161317]] 

[[ 0.14550123  0.08363627  0.20780313 -0.03393091 -0.11775845 -0.45512081
   0.15712041  0.06186619  0.22730926 -0.27642633]
 [ 0.28203271  0.38261101  0.12474022 -0.03776193 -0.10393473  0.00147788
   0.27382914 -0.46347661  0.00451636 -0.46403406]
 [-0.28204966 -0.1859635  -0.11485195  0.24817831  0.37421884 -0.0310524
   0.02443155  0.27265569  0.16353305 -0.46909995]
 [ 0.37311557 -0.08488565 -0.20699128 -0.3312075

In [47]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[4 7 0]
 [2 9 0]
 [0 3 1]]
[[0 3 1]
 [4 7 0]
 [2 9 0]]


In [48]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [49]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.3771626910371938


In [50]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 4. 2. 4. 1. 2. 3. 3. 3. 4.]


In [51]:
print(I)

[9 0 3 8 1 0 3 6 7 2 8 7 1 6 3 1 5 9 0 9]


In [52]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [53]:
w,h = 16,16
img = np.random.randint(0,2,(h,w,3))
np.unique(img.reshape(-1, 3), axis=0)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [54]:
img.shape

(16, 16, 3)

In [55]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(A)
print(sum)

[[[[2 3 3 8]
   [4 8 0 1]
   [6 5 8 0]]

  [[8 7 1 7]
   [8 6 6 7]
   [5 1 6 1]]

  [[5 5 2 6]
   [5 2 5 7]
   [3 7 1 1]]

  [[7 9 9 2]
   [2 8 3 0]
   [7 6 8 6]]]


 [[[5 2 6 2]
   [6 3 6 7]
   [7 1 2 5]]

  [[2 0 1 3]
   [0 8 7 9]
   [1 6 4 5]]

  [[9 1 0 5]
   [6 9 4 1]
   [0 9 6 1]]

  [[2 8 4 3]
   [0 6 7 3]
   [7 2 3 1]]]


 [[[0 6 8 3]
   [3 8 8 3]
   [9 8 0 6]]

  [[2 3 9 2]
   [3 7 9 4]
   [7 9 7 7]]

  [[8 8 3 8]
   [0 6 6 3]
   [5 2 0 6]]

  [[2 5 3 2]
   [8 9 8 5]
   [1 1 8 1]]]]
[[48 63 49 67]
 [52 46 51 46]
 [62 69 55 53]]


In [56]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.64241949 0.32756255 0.62660786 0.50522792 0.60946981 0.64459197
 0.3898207  0.49164144 0.46343439 0.49941558]


In [57]:
A=np.random.randn(100).reshape(5,20)
B=np.random.randn(100).reshape(20,5)
np.diag(np.dot(A, B))

array([ 0.09110389, -1.01544258,  4.38619618,  8.44420699, -4.95385314])

In [58]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
print(Z0)
Z0[::nz+1] = Z
print(Z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [59]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [60]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [61]:
faces = np.random.randint(0,100,(10,3))

In [62]:
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 42) ( 0, 79) ( 3, 17) ( 3, 63) ( 4, 29) ( 4, 83) (14, 70) (14, 95)
 (17, 19) (17, 37) (17, 63) (19, 37) (25, 68) (25, 85) (29, 83) (38, 60)
 (38, 79) (39, 78) (39, 88) (40, 75) (40, 89) (42, 79) (45, 50) (50, 50)
 (60, 79) (68, 85) (70, 95) (75, 89) (78, 88)]


In [63]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [64]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [65]:
def rolling(a,n):
    b=np.array(a[:n])
    for i in range(1,len(a)-n+1):
        b=np.append(b,a[i:i+n])
    b=b.reshape(-1,n)
    return b
rolling(np.arange(10),3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [66]:
a = np.random.randint(0,2,20)
print(a)
print(np.logical_not(a,out=a))
b=np.random.uniform(-1,1,20)
print(b)
print(np.negative(b))

[0 1 0 1 0 0 1 0 0 1 1 0 0 1 0 0 1 1 0 0]
[1 0 1 0 1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 1]
[-0.73681381  0.75691884 -0.03743513  0.33707518 -0.62909355 -0.19901469
  0.56913919 -0.91440132  0.7345516   0.49084525  0.31288326 -0.02529844
  0.41979734  0.88856695  0.13854628  0.7196701  -0.3852411  -0.29167479
  0.55294274 -0.60453949]
[ 0.73681381 -0.75691884  0.03743513 -0.33707518  0.62909355  0.19901469
 -0.56913919  0.91440132 -0.7345516  -0.49084525 -0.31288326  0.02529844
 -0.41979734 -0.88856695 -0.13854628 -0.7196701   0.3852411   0.29167479
 -0.55294274  0.60453949]


In [67]:
#Q69
def dis(p0,p1,p):
    l0=[]
    l1=[]
    for i in p0:
        l0.append(np.sqrt((i[0]-p[0])**2+(i[1]-p[1])**2))
    for i in p1:
        l1.append(np.sqrt((i[0]-p[0])**2+(i[1]-p[1])**2))
    return (min(l0),min(l1))

In [68]:
p0=np.random.uniform(-10,10,(10,2))
p1=np.random.uniform(-10,10,(10,2))
p=(0,0)

In [69]:
dis(p0,p1,p)

(0.44510644990528303, 5.016198583421576)

In [70]:
#Q70
p=np.random.uniform(-10,10,(5,2))
for i in p:
    print(dis(p0,p1,i))

(2.2471654606668667, 3.0514823925478107)
(2.641348032702575, 0.7803914853990631)
(2.6512526801462544, 2.8829252761371835)
(1.363432697904435, 1.1221932183336911)
(8.611853076179823, 5.29769537737671)


In [83]:
Z=list(np.arange(1,15))
print(Z)
a=[]
for i in range(len(Z)-4):
    b=Z[i:i+4]
    a.append(b)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12], [10, 11, 12, 13]]


In [92]:
Z = np.random.uniform(0,1,(10,10))
r=np.linalg.matrix_rank(Z)
r

10

In [112]:
import collections
Z = np.random.randint(0,10,50)
count=dict(collections.Counter(Z))
print(count)
val,ind=list(count.values()),list(count.keys())
print(ind[val.index(max(val))])

{9: 7, 3: 2, 6: 6, 1: 3, 2: 7, 0: 7, 5: 5, 7: 7, 8: 4, 4: 2}
9
