In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/surya/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/surya/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/surya/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

In [3]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [7]:
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [9]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.78741041 0.90844907 0.11761083]
  [0.94910872 0.61912158 0.69271851]
  [0.07904448 0.52044887 0.05476299]]

 [[0.48113494 0.83292943 0.44294313]
  [0.9302114  0.12080963 0.44820343]
  [0.34537291 0.94989941 0.16647553]]

 [[0.53405083 0.5584311  0.5613487 ]
  [0.75354857 0.88040543 0.80925153]
  [0.50680486 0.83986323 0.50946172]]]


In [11]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.025745418703822298 0.9604472893150472


In [12]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.43553548581727003


In [13]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0

In [14]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [15]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [16]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [18]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.60496135 0.85959658 0.9723057  0.46091585 0.        ]
 [0.54036695 0.71006909 0.6618932  0.96146239 0.47046225]
 [0.92710762 0.44900225 0.9259384  0.81973575 0.07925053]
 [0.41775257 0.21548504 0.28830349 1.         0.82038604]
 [0.69961117 0.14016518 0.23855923 0.96597515 0.87258454]]


In [20]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [21]:
np.sum(range(5),-1)

10

In [22]:
sum(range(5),-1)

9

In [23]:
help(np.sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

In [24]:
print(np.array(0) // np.array(0))
print(np.array(0) // np.array(0.))
print(np.array(0) / np.array(0))
print(np.array(0) / np.array(0.))

0
nan
nan
nan


<ipython-input-24-b7aafe4ac6f2>:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-24-b7aafe4ac6f2>:2: RuntimeWarning: invalid value encountered in floor_divide
  print(np.array(0) // np.array(0.))
<ipython-input-24-b7aafe4ac6f2>:3: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-24-b7aafe4ac6f2>:4: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0.))


In [25]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[8. 1. 3. 7. 7. 7. 2. 7. 7. 0.]
[8. 1. 3. 7. 7. 7. 2. 7. 7. 0.]
[8. 1. 3. 7. 7. 7. 2. 7. 7. 0.]
[8 1 3 7 7 7 2 7 7 0]
[8. 1. 3. 7. 7. 7. 2. 7. 7. 0.]


In [26]:
Z = np.zeros((5,5))
Z = Z+np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [27]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [28]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [29]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.10035946 0.1586535  0.29839668 0.32402807 0.39980455 0.42619765
 0.55556976 0.63575399 0.65944013 0.71762688]


In [30]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [31]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.all(A==B)

False

In [32]:
Z = np.zeros(10)
Z.flags.writeable = False
#Z[0] = 1

In [33]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.86970375 0.95200147 0.76711898 0.87373651 0.38980781 0.34817215
 1.11037484 1.01015097 0.92170348 0.91463597]
[1.23564024 1.08254104 0.69528739 0.1778273  1.2607639  0.05360714
 1.03761582 0.50880644 0.74566577 0.97831101]


In [34]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.63487837 1.05963936 1.13474921 1.28309087 0.37408899 0.63665595
 0.90126931 0.96974377 0.49446214 0.41929496]
[0.04959621 0.61360614 0.73292379 0.7788836  0.99619017 0.18106358
 1.38264383 0.36302037 1.34067598 1.05921187]


In [35]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [36]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [37]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [38]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [39]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

41


In [40]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),
                  ('color', [ ('r', float, 1),('g', float, 1),('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-40-183244f52be5>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),


In [41]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
D.shape

(10, 10)

In [42]:
Z = np.arange(10, dtype=np.int32)
print(Z)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [43]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [44]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [45]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),100)
print(Z)

[[  0.   0.   0. 100.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. 100.   0.   0.   0.   0.   0.   0.   0.]]


In [46]:
X = np.random.rand(5, 10)
print(X,"\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.94620003 0.49046739 0.24853509 0.29733223 0.89038855 0.94821697
  0.74394422 0.34374592 0.34568353 0.17373534]
 [0.96321122 0.6688499  0.7237509  0.18810168 0.61722566 0.02967782
  0.54594066 0.35720221 0.16474188 0.66651504]
 [0.23114241 0.38742223 0.69554238 0.48674106 0.6198297  0.14869506
  0.2610392  0.88828321 0.16690791 0.38202148]
 [0.00133301 0.63324625 0.02623821 0.27129685 0.1882843  0.37887226
  0.30492103 0.4215788  0.11376315 0.42005147]
 [0.94953967 0.26798289 0.23238091 0.02495053 0.70375181 0.36970919
  0.50058793 0.64811907 0.40706703 0.5539617 ]] 

[[ 0.4033751  -0.05235754 -0.29428983 -0.2454927   0.34756362  0.40539205
   0.2011193  -0.199079   -0.1971414  -0.36908959]
 [ 0.47068952  0.1763282   0.2312292  -0.30442002  0.12470396 -0.46284388
   0.05341896 -0.13531948 -0.32777981  0.17399334]
 [-0.19562005 -0.03934023  0.26877992  0.05997859  0.19306724 -0.2780674
  -0.16572327  0.46152075 -0.25985455 -0.04474098]
 [-0.27462552  0.35728771 -0.24972032 -0.0046616

In [47]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 1 9]
 [5 5 0]
 [9 1 3]]
[[8 1 9]
 [9 1 3]
 [5 5 0]]


In [48]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [49]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.49906388507795374


In [50]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 3. 2. 4. 2. 2. 3. 4. 4.]


In [51]:
print(I)

[6 2 7 4 8 7 9 8 9 3 2 1 9 0 0 5 1 8 4 4]


In [52]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [53]:
w,h = 16,16
img = np.random.randint(0,2,(h,w,3))
np.unique(img.reshape(-1, 3), axis=0)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [54]:
img.shape

(16, 16, 3)

In [55]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(A)
print(sum)

[[[[7 5 2 1]
   [4 8 1 1]
   [4 7 0 8]]

  [[2 3 0 4]
   [7 2 0 2]
   [0 6 5 9]]

  [[2 0 5 5]
   [2 8 9 9]
   [3 5 6 6]]

  [[0 9 3 8]
   [0 6 6 7]
   [7 1 2 6]]]


 [[[2 5 8 7]
   [2 0 6 6]
   [3 0 2 4]]

  [[0 5 5 2]
   [3 8 0 1]
   [0 4 6 6]]

  [[1 2 6 1]
   [1 8 0 5]
   [4 4 8 9]]

  [[3 1 0 8]
   [3 2 4 5]
   [5 6 7 6]]]


 [[[0 7 8 7]
   [6 3 8 0]
   [4 7 1 7]]

  [[0 3 8 2]
   [2 9 3 5]
   [1 3 4 2]]

  [[3 8 1 7]
   [0 9 6 8]
   [8 3 1 7]]

  [[3 3 3 2]
   [5 1 3 9]
   [5 5 1 5]]]]
[[48 40 60 55]
 [45 40 49 50]
 [58 42 61 45]]


In [56]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.42107813 0.59244939 0.46532657 0.36291355 0.52008654 0.5563224
 0.56862145 0.49685196 0.42765535 0.55279926]


In [57]:
A=np.random.randn(100).reshape(5,20)
B=np.random.randn(100).reshape(20,5)
np.diag(np.dot(A, B))

array([-4.77378438,  2.44835631, -5.4856322 , -4.33849951,  0.75832815])

In [58]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
print(Z0)
Z0[::nz+1] = Z
print(Z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [59]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [60]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [61]:
faces = np.random.randint(0,100,(10,3))

In [62]:
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 47) ( 3, 71) (20, 22) (20, 40) (20, 58) (20, 84) (21, 47) (21, 57)
 (22, 58) (23, 25) (23, 96) (25, 96) (30, 77) (30, 93) (35, 83) (35, 98)
 (38, 84) (38, 92) (40, 84) (47, 57) (47, 71) (58, 82) (58, 85) (73, 82)
 (73, 84) (77, 93) (82, 84) (82, 85) (83, 98) (84, 92)]


In [63]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [64]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [65]:
def rolling(a,n):
    b=np.array(a[:n])
    for i in range(1,len(a)-n+1):
        b=np.append(b,a[i:i+n])
    b=b.reshape(-1,n)
    return b
rolling(np.arange(10),3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [66]:
a = np.random.randint(0,2,20)
print(a)
print(np.logical_not(a,out=a))
b=np.random.uniform(-1,1,20)
print(b)
print(np.negative(b))

[1 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1]
[0 1 0 0 1 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0]
[ 0.11274932 -0.50824212 -0.26634506  0.20032222 -0.9780064  -0.54217473
 -0.56020739  0.87359585  0.61665962 -0.10105107  0.02034344 -0.53972432
  0.65560712 -0.45203005  0.40106273  0.76201609 -0.41987479  0.50236543
 -0.19641312  0.62024724]
[-0.11274932  0.50824212  0.26634506 -0.20032222  0.9780064   0.54217473
  0.56020739 -0.87359585 -0.61665962  0.10105107 -0.02034344  0.53972432
 -0.65560712  0.45203005 -0.40106273 -0.76201609  0.41987479 -0.50236543
  0.19641312 -0.62024724]


In [67]:
#Q69
def dis(p0,p1,p):
    l0=[]
    l1=[]
    for i in p0:
        l0.append(np.sqrt((i[0]-p[0])**2+(i[1]-p[1])**2))
    for i in p1:
        l1.append(np.sqrt((i[0]-p[0])**2+(i[1]-p[1])**2))
    return (min(l0),min(l1))

In [68]:
p0=np.random.uniform(-10,10,(10,2))
p1=np.random.uniform(-10,10,(10,2))
p=(0,0)

In [69]:
dis(p0,p1,p)

(5.327211475384173, 3.9290727968635086)

In [70]:
#Q70
p=np.random.uniform(-10,10,(5,2))
for i in p:
    print(dis(p0,p1,i))

(4.505037493665441, 3.0995792325748686)
(5.069122786101537, 1.029652937067798)
(3.647880860011368, 1.2859323773049376)
(6.08437339116851, 3.4537528810124964)
(3.442730504342469, 4.499033389168688)
