## Instructions :
- Only Edit  *YOUR CODE HERE*
- Do not change the assert statements which test your functions

In [1]:
import numpy as np

### Windows and Strides
Given a 1d array, and parameters window_len and stride_len, do the following:
- Divide the 1d array into smaller arrays of size window_len starting at index 0
- move the starting index by step size stride_len each time
- Return all windows as a 2d matrix

Eg.,
Input: <br>
arr = [1, 3, 7, 1, 2, 6, 0, 1]  <br>
stride_len = 2 , window_len = 4

- First window (starting at index 0) should be of len window_len (4) --> [1, 3, 7, 1] <br>
- Move by step size stride_len(2) and take next window --> [7, 1, 2, 6] <br>
and so on..

Output matrix <br>
[[1, 3, 7, 1], <br>
 [7, 1, 2, 6], <br>
 [2, 6, 0, 1]]


In [2]:
def gen_strides(a, stride_len, window_len):
    '''
    Input:
      a: Numpy array of 1 dimension
      stride_len: int, stride length
      window_len : int, window length
    
    Output:
      Numpy array of 2 dimensions containing windowed strides as explained above
    '''
    # YOUR CODE HERE
    result=[]
    temp=[]
    for i in range(0,a.shape[0],stride_len):
        if(i+window_len>a.shape[0]):
            break;
        temp=list(a[i:i+window_len])
        result+=[temp]
    return np.array(result)

In [3]:
"""Test for strides"""
assert np.all(gen_strides(np.array([1, 3, 7, 1, 2, 6, 0, 1]),2,4) == np.array([[1, 3, 7, 1], [7, 1, 2, 6], [2, 6, 0, 1]]))
""
print("Sample Tests passed", '\U0001F44D')

Sample Tests passed 👍


### Shuffle
Given a numpy array of arbitrary dimensions (> 1), shuffle its rows randomly. <br>
Hint - You need to shuffle along axis 0

In [4]:
def shuf(arr):
  '''
  Input: 
    arr: Numpy array of arbitrary number of dimensions (>1)
  Output:
    numpy array of same shape as arr but with rows shuffled
  '''
  # YOUR CODE HERE
  np.random.shuffle(arr)
  return arr

In [5]:
"""Test for shuf"""
arr=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
assert np.any(shuf(np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])) != np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
assert shuf(np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])).shape == np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).shape

print("Sample Tests passed", '\U0001F44D')

Sample Tests passed 👍


### Match
    Get the positions where corresponding elements (same indices) of array a and array b match <br>
    
    Eg. Input <br>
    a = np.array([1,2,3,2,3,4,3,4,5,6]) <br>
    b = np.array([7,2,10,2,7,4,9,4,9,8]) <br>
    
    Desired Output:

    [1, 3, 5, 7])

In [6]:
def match(a,b):
    '''
    Inputs:
      a, b: numpy arrays of same shape of 1 dimension
    Outputs:
      list containing indices where both arrays have same elements
    '''
    # YOUR CODE HERE
#     print(a.shape[0])
    if(a.shape[0]==b.shape[0]):
      li=[]
#       print(a.shape[0])
      for i in range(0,a.shape[0]):
        if(a[i]==b[i]):
          li+=[i]
      return li


In [7]:
"""Test for match"""
assert(match(np.array([1,2,3,2,3,4,3,4,5,6]),np.array([7,2,10,2,7,4,9,4,9,8])) == [1,3,5,7])
print("Sample Tests passed", '\U0001F44D')

Sample Tests passed 👍


In [8]:
def lin_eqn(a,b):
    '''
    Solve the system of linear equations
    of the form ax = b
    
    Eg. 
    
    Solve the system of linear equation
    
    x + 2*y = 8
    3*x + 4*y = 18
    
    Given inputs a and b represent coefficients and constant of linear equation respectively
    
    coefficients: 
    a = np.array([[1, 2], [3, 4]]) 
    
    constants: 
    b = np.array([8, 18])
    
    Desired Output: [2,3]
    

    '''
    # YOUR CODE HERE
    temp=np.linalg.inv(a)
    print(temp.dot(b))
    return temp.dot(b)

In [9]:
x=lin_eqn(np.array([[1.0, 2.0], [3, 4]]),np.array([8.0, 18.0]))
print(x)

[2. 3.]
[2. 3.]


In [10]:
"""My practice Test for lin_eqn"""
"""My practice Test for lin_eqn"""
"""My practice Test for lin_eqn"""
assert np.any(lin_eqn(np.array([[1, 2], [3, 4]]),np.array([8, 18])) == np.array([2., 3.]))

print("Sample Tests passed", '\U0001F44D')


[2. 3.]
Sample Tests passed 👍


In [11]:
def inv(arr):
    """
    Given an array arr (square matrix), find its inverse
    """
    # YOUR CODE HERE
    if(arr.shape[0]==arr.shape[1]):
      return np.linalg.inv(arr)

In [12]:
print(inv(np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [13]:
"""Test for inv"""
assert np.all(np.isclose(inv(np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])).tolist(), np.array([[0.17647058823529413, -0.0032679738562091526, -0.02287581699346405],[0.05882352941176469, -0.130718954248366, 0.0849673202614379],[-0.1176470588235294, 0.1503267973856209, 0.0522875816993464]])))

print("Sample Tests passed", '\U0001F44D')


Sample Tests passed 👍


### rankArray
Rank the items in a multidimensional array 'arr'. <br>
The rank of an item is its index in the sorted list of all items in 'arr' (starting from 0). <br>
          Eg., consider arr = [0, 6, 14, 12, 11] <br>
                  arr_sorted = [0, 6, 11, 12, 14] <br>
                  So rank of 0 -> 0; 6->1; 11->2, 12->3, 14->4 <br>
                  rankArray returns a list where each element is replaced by its rank <br>
                  rankArray(arr) -> [0, 1, 4, 3, 2] <br>
                  
==========================================    
Another example, <br>
Eg: 

arr = [[ 9  4 15  0 17], [16 17  8  9  0]] ... (2X5 array) <br>

Desired output: <br>
[[4 2 6 0 8], [7 9 3 5 1]] ... (2X5 array) <br>

Here minimum value in arr is 0 at (0,3), so rank the index of 0 in output matrix as 0 <br>
i.e. out[0][3] = 0 <br>
Next minimum is also 0 at index (1,4), so rank the index (1,4) in output matrix as 1 and so on...

=============================================
If two elements repeat; for eg., both a1 = arr[0, 1, 2, 4] and a2 = arr[0, 1, 3, 2] are equal to 1, then rank of the a1 is lower than the rank of a2 because at the first index at which they differ, the index of a1 is lower than that of a2 (similar to lexicographical ordering)


In [14]:
import numpy as np

def rankArray(arr):
    '''
    Input:
        arr: Numpy array of arbitrary dimensions 
    Output:
        numpy array of same shape as arr but with elements replaced by their ranks
    '''
    # YOUR CODE HERE
    li=list(np.sort(arr.flatten()))
    for i in range(0,arr.shape[0]):
      for j in range(0,arr.shape[1]):
        for h in range(0,len(li)):
          if(arr[i][j]==li[h]):
            arr[i][j]=h
            li[h]="#"
            break
    return arr

In [15]:
print(rankArray(np.array([[9, 4, 15, 0, 17], [16,17,8,9,0]])).tolist())

[[4, 2, 6, 0, 8], [7, 9, 3, 5, 1]]


In [16]:
"""Test for rankArray"""
assert np.all(rankArray(np.array([[9, 4, 15, 0, 17], [16,17,8,9,0]])) == np.array([[4,2, 6, 0, 8], [7, 9, 3, 5, 1]]).tolist())
print("Sample Tests passed", '\U0001F44D')

Sample Tests passed 👍
